
package vista.pacientes;

import controlador.PacienteCoontrolador;
import javax.swing.table.DefaultTableModel;
import modelo.PacienteModelo;

public class Listado extends javax.swing.JInternalFrame {
    
    public DefaultTableModel tableModel=new DefaultTableModel();
    PacienteCoontrolador  pc=PacienteCoontrolador.getInstacia();
    
    public Listado() {
        initComponents();
        
        
        tbl_listado.setModel(tableModel);
        String columnas[]={"CEDULA","NOMBRES","EDAD","SEXO"};
        tableModel.setColumnIdentifiers(columnas);
        
        cargarListadoPacientes();
        
        
        
        
    }

    private void cargarListadoPacientes(){
        for (PacienteModelo pm : pc.listadoCompleto()) {
            Object[] fila={pm.getCedula(),pm.getNombres(),pm.getEdad(),pm.getSexo()};
            tableModel.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_buscar_por_cedula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listado = new javax.swing.JTable();

        jLabel1.setText("BUSCAR POR CEDULA.");

        txt_buscar_por_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscar_por_cedulaKeyReleased(evt);
            }
        });

        tbl_listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_listado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscar_por_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_buscar_por_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscar_por_cedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_por_cedulaKeyReleased
        
        tableModel.setRowCount(0);
        
        String cedula=txt_buscar_por_cedula.getText();
        
        
        for (PacienteModelo pm : pc.listadoCompletoPorCedula(cedula)) {
            Object[] fila={pm.getCedula(),pm.getNombres(),pm.getEdad(),pm.getSexo()};
            tableModel.addRow(fila);
        }
        
        
    }//GEN-LAST:event_txt_buscar_por_cedulaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_listado;
    private javax.swing.JTextField txt_buscar_por_cedula;
    // End of variables declaration//GEN-END:variables
}
