/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import vista.pacientes.Ingresar;
import vista.pacientes.Listado;

/**
 *
 * @author Laboratorios DCCO
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor_principal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menu_ingresar_paciente = new javax.swing.JMenuItem();
        menu_listado_paciente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_ingresar_especialidad = new javax.swing.JMenuItem();
        menu_listado_especialidad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_ingresar_medico = new javax.swing.JMenuItem();
        menu_listado_medico = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menu_ingreasar_citas = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout contenedor_principalLayout = new javax.swing.GroupLayout(contenedor_principal);
        contenedor_principal.setLayout(contenedor_principalLayout);
        contenedor_principalLayout.setHorizontalGroup(
            contenedor_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        contenedor_principalLayout.setVerticalGroup(
            contenedor_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jMenu1.setText("INICIO");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("PACIENTES");

        menu_ingresar_paciente.setText("INGRESAR");
        menu_ingresar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ingresar_pacienteActionPerformed(evt);
            }
        });
        jMenu2.add(menu_ingresar_paciente);

        menu_listado_paciente.setText("LISTADO");
        menu_listado_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listado_pacienteActionPerformed(evt);
            }
        });
        jMenu2.add(menu_listado_paciente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("ESPECIALIDADES");

        menu_ingresar_especialidad.setText("INGRESAR");
        menu_ingresar_especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ingresar_especialidadActionPerformed(evt);
            }
        });
        jMenu3.add(menu_ingresar_especialidad);

        menu_listado_especialidad.setText("LISTADO");
        menu_listado_especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listado_especialidadActionPerformed(evt);
            }
        });
        jMenu3.add(menu_listado_especialidad);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("MEDICOS");

        menu_ingresar_medico.setText("INGRESAR");
        menu_ingresar_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ingresar_medicoActionPerformed(evt);
            }
        });
        jMenu4.add(menu_ingresar_medico);

        menu_listado_medico.setText("LISTADO");
        menu_listado_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listado_medicoActionPerformed(evt);
            }
        });
        jMenu4.add(menu_listado_medico);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("CITAS");

        menu_ingreasar_citas.setText("INGRESAR");
        menu_ingreasar_citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ingreasar_citasActionPerformed(evt);
            }
        });
        jMenu5.add(menu_ingreasar_citas);

        jMenuItem8.setText("LISTAR");
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor_principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_ingresar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ingresar_pacienteActionPerformed
        // cargue la pantalla de ingresar. view.pacientes
        contenedor_principal.removeAll();
        Ingresar  i= new Ingresar();
        contenedor_principal.add(i).setVisible(true);
        
    }//GEN-LAST:event_menu_ingresar_pacienteActionPerformed

    private void menu_listado_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listado_pacienteActionPerformed
        contenedor_principal.removeAll();
        contenedor_principal.add(new Listado()).setVisible(true);
    }//GEN-LAST:event_menu_listado_pacienteActionPerformed

    private void menu_ingresar_especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ingresar_especialidadActionPerformed
        contenedor_principal.removeAll();
        contenedor_principal.add(new vista.especialidades.Ingresar()).setVisible(true);
    }//GEN-LAST:event_menu_ingresar_especialidadActionPerformed

    private void menu_listado_especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listado_especialidadActionPerformed
         contenedor_principal.removeAll();
        contenedor_principal.add(new vista.especialidades.Listado()).setVisible(true);
    }//GEN-LAST:event_menu_listado_especialidadActionPerformed

    private void menu_ingresar_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ingresar_medicoActionPerformed
         contenedor_principal.removeAll();
        contenedor_principal.add(new vista.medicos.Ingresar()).setVisible(true);
    }//GEN-LAST:event_menu_ingresar_medicoActionPerformed

    private void menu_listado_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listado_medicoActionPerformed
       contenedor_principal.removeAll();
        contenedor_principal.add(new vista.medicos.Listado()).setVisible(true);
    }//GEN-LAST:event_menu_listado_medicoActionPerformed

    private void menu_ingreasar_citasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ingreasar_citasActionPerformed
        contenedor_principal.removeAll();
        contenedor_principal.add(new vista.citas.Ingresar()).setVisible(true);
    }//GEN-LAST:event_menu_ingreasar_citasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane contenedor_principal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem menu_ingreasar_citas;
    private javax.swing.JMenuItem menu_ingresar_especialidad;
    private javax.swing.JMenuItem menu_ingresar_medico;
    private javax.swing.JMenuItem menu_ingresar_paciente;
    private javax.swing.JMenuItem menu_listado_especialidad;
    private javax.swing.JMenuItem menu_listado_medico;
    private javax.swing.JMenuItem menu_listado_paciente;
    // End of variables declaration//GEN-END:variables
}
